name = "rusty_luau/std"
version = "0.0.1"
description = "Porting Rust's idioms into Luau"
authors = ["word30210 <wordisnottoto@gmail.com>"]
repository = "https://github.com/rusty-luau/std"
license = "MIT"
includes = [
    "src/**",
    "pesde.toml",
    "README.md",
    "LICENSE",
    "assets/**"
]

[target]
environment = "luau"
lib = "src/lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
