name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'scripts/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'scripts/**'
      - '.github/workflows/ci.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6

      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install: true
          
      - name: Run checker
        run: lute run ./scripts/checker.luau -- ./src ./tests ./scripts
  
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6

      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install: true
          
      - name: Run unit tests
        run: lute run ./scripts/tester.luau